version: '3'
services:
  web:
    build: frontend/web_client
    ports:
      - "23333:80"
    depends_on:
      - web-interface
  web-interface:
    build: backend/web-interface
    ports:
      - "8888:8888"
    depends_on:
      - mongo
  crawler:
    build: backend/crawler
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    